src/Entity/ModeleOffreCommerciale.php
<?php

namespace App\Entity;

use App\Repository\ModeleOffreCommercialeRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ModeleOffreCommercialeRepository::class)
 */
class ModeleOffreCommerciale
{
    use ResourceId;
    use Timestapable;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     * @Assert\Length(
     *      min = 2,
     *      max = 50,
     *      minMessage = "un minimum de {{ limit }} caractères est requis",
     *      maxMessage = "{{ limit }} caractères sont la limite"
     * )
     */
    private string $name;

    /**
     * @ORM\Column(type="integer", length=255, nullable=true)
     */
    private ?int $nombre_offres;

    /**
     * @ORM\Column(type="boolean")
     */
    private bool $isCvTheque;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private string $dureeContrat;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Regex(
     *     pattern = "/^[0-9]+$/i",
     *     message = "Seul les chiffres sont acceptés",
     * )
     */
    private string $prix;

    /**
     * @ORM\Column(type="integer", length=255, nullable=true)
     */
    private ?int $nombre_recruteurs;

    /**
     * @ORM\OneToMany(targetEntity=Offre::class, mappedBy="modele_offre_commerciale", cascade={"persist", "remove"})
     */
    private ?Collection $offre;

    /**
     * @ORM\Column(type="string", length=255)
     * @Gedmo\Slug(fields={"name"})
     */
    private ?string $slug;

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getNombreOffres(): ?string
    {
        return $this->nombre_offres;
    }

    public function setNombreOffres(string $nombre_offres): self
    {
        $this->nombre_offres = $nombre_offres;

        return $this;
    }

    public function getIsCvTheque(): ?bool
    {
        return $this->isCvTheque;
    }

    public function setIsCvTheque(bool $isCvTheque): self
    {
        $this->isCvTheque = $isCvTheque;

        return $this;
    }

    public function getDureeContrat(): ?string
    {
        return $this->dureeContrat;
    }

    public function setDureeContrat(string $dureeContrat): self
    {
        $this->dureeContrat = $dureeContrat;

        return $this;
    }

    public function getPrix(): ?string
    {
        return $this->prix;
    }

    public function setPrix(string $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getNombreRecruteurs(): ?string
    {
        return $this->nombre_recruteurs;
    }

    public function setNombreRecruteurs(?string $nombre_recruteurs): self
    {
        $this->nombre_recruteurs = $nombre_recruteurs;

        return $this;
    }

    public function getOffre(): ?Offre
    {
        return $this->offre;
    }

    public function setOffre(?Offre $offre): self
    {
        // unset the owning side of the relation if necessary
        if ($offre === null && $this->offre !== null) {
            $this->offre->setModeleOffreCommerciale(null);
        }

        // set the owning side of the relation if necessary
        if ($offre !== null && $offre->getModeleOffreCommerciale() !== $this) {
            $offre->setModeleOffreCommerciale($this);
        }

        $this->offre = $offre;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }
}

src/Form/ModeleOffreCommercialeType.php
<?php

namespace App\Form;

use App\Entity\ModeleOffreCommerciale;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\NotNull;

class ModeleOffreCommercialeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class, [
                'label' => 'Nom',
                'constraints' => [
                    new NotNull([
                        'message' => 'Veuillez saisir un nom',
                    ]),
                ],
            ])
            ->add('slug', TextType::class, [
                'label' => 'Slug',
                'constraints' => [
                    new NotNull([
                        'message' => 'Veuillez saisir un slug',
                    ]),
                ],
            ])
            ->add('nombre_offres', IntegerType::class,[
                'required' => false
            ])
            ->add('isCvTheque')
            ->add('nombreRecruteurs', IntegerType::class, [
                'required' => false
            ])
            ->add('dureeContrat', TextType::class, [
                'required' => true,
                'label' => 'Duréee de contrat',
                'attr' => [
                    'placeholder' => 'En mois'
                ]
            ])
            ->add('prix', TextType::class, [
                'label' => 'Prix',
                'constraints' => [
                    new NotNull([
                        'message' => 'Veuillez saisir un prix',
                    ]),
                ],
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => ModeleOffreCommerciale::class,
        ]);
    }
}

src/Controller/ModeleOffreCommercialeController.php
<?php

namespace App\Controller;

use App\Entity\ModeleOffreCommerciale;
use App\Form\ModeleOffreCommercialeType;
use App\Repository\ModeleOffreCommercialeRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/cms/modele-offre-commerciale')]
class ModeleOffreCommercialeController extends AbstractController
{
    #[Route('/', name: 'modele_offre_commerciale_index', methods: ['GET'])]
    public function index(Request $request, ModeleOffreCommercialeRepository $modeleOffreCommercialeRepository, PaginatorInterface $paginator): Response
    {
        $this->denyAccessUnlessGranted('ROLE_RECRUTEUR');

        $data = $modeleOffreCommercialeRepository->findAll();
        $modeles = $paginator->paginate(
            $data,
            $request->query->getInt('page', 1),
            4
        );
        return $this->render('modele_offre_commerciale/index.html.twig', [
            'modele_offre_commerciales' => $modeles,
        ]);
    }

    #[Route('/new', name: 'modele_offre_commerciale_new', methods: ['GET', 'POST'])]
    public function new(Request $request): Response
    {
        $this->denyAccessUnlessGranted('ROLE_RECRUTEUR');

        $modeleOffreCommerciale = new ModeleOffreCommerciale();
        $form = $this->createForm(ModeleOffreCommercialeType::class, $modeleOffreCommerciale);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($modeleOffreCommerciale);
            $entityManager->flush();

            $this->addFlash('success', 'Ajout réussi');

            return $this->redirectToRoute('modele_offre_commerciale_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('modele_offre_commerciale/new.html.twig', [
            'modele_offre_commerciale' => $modeleOffreCommerciale,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/{id}', name: 'modele_offre_commerciale_show', methods: ['GET'])]
    public function show(ModeleOffreCommerciale $modeleOffreCommerciale): Response
    {
        $this->denyAccessUnlessGranted('ROLE_RECRUTEUR');

        return $this->render('modele_offre_commerciale/show.html.twig', [
            'modele_offre_commerciale' => $modeleOffreCommerciale,
        ]);
    }

    #[Route('/{id}/edit', name: 'modele_offre_commerciale_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, ModeleOffreCommerciale $modeleOffreCommerciale): Response
    {
        $this->denyAccessUnlessGranted('ROLE_RECRUTEUR');

        $form = $this->createForm(ModeleOffreCommercialeType::class, $modeleOffreCommerciale);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $modeleOffreCommerciale->updateTimestamps();
            $this->getDoctrine()->getManager()->flush();

            $this->addFlash('success', 'Mise à jour réussie');

            return $this->redirectToRoute('modele_offre_commerciale_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('modele_offre_commerciale/edit.html.twig', [
            'modele_offre_commerciale' => $modeleOffreCommerciale,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/{id}', name: 'modele_offre_commerciale_delete', methods: ['POST'])]
    public function delete(Request $request, ModeleOffreCommerciale $modeleOffreCommerciale): Response
    {
        $this->denyAccessUnlessGranted('ROLE_RECRUTEUR');

        if ($this->isCsrfTokenValid('delete'.$modeleOffreCommerciale->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($modeleOffreCommerciale);
            $entityManager->flush();
        }

        return $this->redirectToRoute('modele_offre_commerciale_index');
    }
}

templates/modele_offre_commerciale/_delete_form.html.twig
<form method="post" action="{{ path('modele_offre_commerciale_delete', {'id': modele_offre_commerciale.id}) }}" onsubmit="return confirm('êtes-vous sûr de vouloir supprimer ce modèle?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ modele_offre_commerciale.id) }}">
    <button class="btn"><i class="fas fa-trash"></i></button>
</form>

templates/modele_offre_commerciale/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <input type="submit" value="Enregistrer" class="bouton solid" />
{{ form_end(form) }}

templates/modele_offre_commerciale/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit ModeleOffreCommerciale{% endblock %}

{% block body %}
<main id="main">
    <!-- ======= Breadcrumbs ======= -->
    <section id="breadcrumbs" class="breadcrumbs">
        <div class="container">
            <ol>
                <li><a href="{{ path('app_home') }}">Home</a></li>
                <li><a href="{{ path('app_profile') }}">Dashboard</a></li>
                <li><a href="{{ path('menu_index') }}">Modèles d'offres</a></li>
                <li>Modification</li>
            </ol>
            <h1>Modification du modèle "{{ modele_offre_commerciale.name }}"</h1>
        </div>
    </section><!-- End Breadcrumbs -->
    <section class="inner-page">
        <div class="container">
            <div class="row">
                <div class="col-md-3">
                    {% include('layouts/_dash_sidebar.html.twig') %}
                </div>
                <div class="col-md-9">
                    {{ include('modele_offre_commerciale/_form.html.twig', {'button_label': 'Enregistrer'}) }}
                </div>
            </div>
        </div>
    </section>
</main>
{% endblock %}

templates/modele_offre_commerciale/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}ModeleOffreCommerciale index{% endblock %}

{% block body %}
<main id="main">
    <!-- ======= Breadcrumbs ======= -->
    <section id="breadcrumbs" class="breadcrumbs">
        <div class="container">
            <ol>
                <li><a href="{{ path('app_home') }}">Home</a></li>
                <li><a href="{{ path('app_profile') }}">Dashboard</a></li>
                <li><a href="{{ path('menu_index') }}">Modèles d'offres</a></li>
                <li>Répértoire</li>
            </ol>
            <h1>Modèles d'offres commerciales</h1>
        </div>
    </section><!-- End Breadcrumbs -->
    <section class="inner-page">
        <div class="container">
            <div class="row">
                <div class="col-md-3">
                    {% include('layouts/_dash_sidebar.html.twig') %}
                </div>
                <div class="col-md-9">
                    <a class="btn app-btn-primary mb-4" href="{{ path('modele_offre_commerciale_new') }}">
                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-file-earmark-arrow-down me-2" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path d="M8 0a1 1 0 0 1 1 1v6h6a1 1 0 1 1 0 2H9v6a1 1 0 1 1-2 0V9H1a1 1 0 0 1 0-2h6V1a1 1 0 0 1 1-1z"/>
                        </svg>Ajouter
                    </a>
                     <table class="table" id="datatable">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Slug</th>
                                <th>Nombre d'offres</th>
                                <th>Nombre de recruteurs</th>
                                <th>IsCvTheque</th>
                                <th>DureeContrat</th>
                                <th>Prix</th>
                                <th>actions</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for modele_offre_commerciale in modele_offre_commerciales %}
                            <tr>
                                <td><a href="{{ path('modele_offre_commerciale_show', {'id': modele_offre_commerciale.id}) }}">{{ modele_offre_commerciale.name }}</a></td>
                                <td>{{ modele_offre_commerciale.slug }}</td>
                                <td>{{ modele_offre_commerciale.nombreOffres }}</td>
                                <td>{{ modele_offre_commerciale.nombreRecruteurs }}</td>
                                <td>{{ modele_offre_commerciale.isCvTheque ? 'Yes' : 'No' }}</td>
                                <td>{{ modele_offre_commerciale.dureeContrat }}</td>
                                <td>{{ modele_offre_commerciale.prix }}</td>
                                <td>
                                    <div class="d-flex justify-content-around">
                                        <a href="{{ path('modele_offre_commerciale_edit', {'id': modele_offre_commerciale.id}) }}" class="d-flex align-items-center"><i class="fas fa-edit"></i></a>
                                        {{ include('modele_offre_commerciale/_delete_form.html.twig') }}
                                    </div>
                                </td>
                            </tr>
                        {% else %}
                            <tr>
                                <td colspan="7">no records found</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>
</main>
{% endblock %}

templates/modele_offre_commerciale/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New ModeleOffreCommerciale{% endblock %}

{% block body %}
<main id="main">
    <!-- ======= Breadcrumbs ======= -->
    <section id="breadcrumbs" class="breadcrumbs">
        <div class="container">
            <ol>
                <li><a href="{{ path('app_home') }}">Home</a></li>
                <li>Dashboard</li>
            </ol>
            <h1>Création Modèle Offre Commerciale</h1>

        </div>
    </section><!-- End Breadcrumbs -->
    <section class="inner-page">
        <div class="container">
            <div class="row">
                <div class="col-md-3">
                    {% include('layouts/_dash_sidebar.html.twig') %}
                </div>
                <div class="col-md-9">
                    {{ include('modele_offre_commerciale/_form.html.twig') }}
                </div>
            </div>
        </div>
    </section>
</main>
{% endblock %}

templates/modele_offre_commerciale/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}ModeleOffreCommerciale{% endblock %}

{% block body %}
<main id="main">
    <!-- ======= Breadcrumbs ======= -->
    <section id="breadcrumbs" class="breadcrumbs">
        <div class="container">
            <ol>
                <li><a href="{{ path('app_home') }}">Home</a></li>
                <li><a href="{{ path('app_profile') }}">Dashboard</a></li>
                <li><a href="{{ path('menu_index') }}">Modèles d'offres</a></li>
                <li>Lecture</li>
            </ol>
            <h1>{{ modele_offre_commerciale.name }}</h1>
        </div>
    </section><!-- End Breadcrumbs -->
    <section class="inner-page">
        <div class="container">

            <table class="table">
                <tbody>
                    <tr>
                        <th>Nom</th>
                        <td>{{ modele_offre_commerciale.name }}</td>
                    </tr>
                    <tr>
                        <th>Nombre d'offres</th>
                        <td>{{ modele_offre_commerciale.nombreOffres }}</td>
                    </tr>
                    <tr>
                        <th>CVthèque</th>
                        <td>{{ modele_offre_commerciale.isCvTheque ? 'Yes' : 'No' }}</td>
                    </tr>
                    <tr>
                        <th>Durée de contrat</th>
                        <td>{{ modele_offre_commerciale.dureeContrat }}</td>
                    </tr>
                    <tr>
                        <th>Prix</th>
                        <td>{{ modele_offre_commerciale.prix }}€</td>
                    </tr>
                </tbody>
            </table>
            <di>
                {{ include('modele_offre_commerciale/_delete_form.html.twig') }}
            </di>
        </div>
    </section>
</main>

{% endblock %}